image: silkeh/clang

build:
  stage: build
  script:
    - cmake . -B out/gitlab
    - cmake --build out/gitlab --target all
    - cd out/giltab
    - ctest
    - cd smaep_cli
    - ./smaep_cli -a "2 * (3 + 4)"

